language: php
php:
  - 5.6
  - nightly

before_script:
  ./composer.phar update
script:
  - ./vendor/bin/phploc --count-tests ./src
  - ./vendor/bin/phpunit --configuration build/phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=autoload.php ./src
