language: php
php:
  - 5.6
  - nightly

before_script:
  ./composer.phar update
script:
  - phpunit --configuration build/phpunit.xml
  - ./vendor/bin/phpcs --standard=PSR2 --extensions=php --ignore=autoload.php ./src ./tests
